; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp> -<encoder_test.cpp> -<calibration_test.cpp> -<pin_test.cpp> -<pid_tuner.cpp> -<motor_encoder_test.cpp> -<velocity_control_test.cpp> -<differential_drive_test.cpp>

[env:encoder_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<encoder_test.cpp> -<main.cpp>

[env:pin_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<pin_test.cpp> -<main.cpp> -<encoder_test.cpp>

[env:calibration]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<calibration_test.cpp> -<main.cpp> -<encoder_test.cpp> -<pin_test.cpp>

[env:pid_tuner]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<pid_tuner.cpp> -<main.cpp> -<encoder_test.cpp> -<pin_test.cpp> -<calibration_test.cpp> -<motor_encoder_test.cpp>

[env:motor_encoder_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<motor_encoder_test.cpp> -<main.cpp> -<encoder_test.cpp> -<pin_test.cpp> -<calibration_test.cpp> -<pid_tuner.cpp> -<velocity_control_test.cpp>

[env:velocity_control_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<velocity_control_test.cpp> -<main.cpp> -<encoder_test.cpp> -<pin_test.cpp> -<calibration_test.cpp> -<pid_tuner.cpp> -<motor_encoder_test.cpp> -<differential_drive_test.cpp>

[env:differential_drive_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = +<differential_drive_test.cpp> -<main.cpp> -<encoder_test.cpp> -<pin_test.cpp> -<calibration_test.cpp> -<pid_tuner.cpp> -<motor_encoder_test.cpp> -<velocity_control_test.cpp>
